// js/utils/commands.js

window.COMMANDS = [
    { cmd: '/help',         desc: 'Show available commands' },
    { cmd: '/clear',        desc: 'Clear chat history (local only)' },
    { cmd: '/fetch',        desc: 'Refresh the repository file tree' },
    { cmd: '/open',         desc: 'Load a file into chat (Usage: /open <path>)' },
    { cmd: '/commit',       desc: 'Commit last open file (Usage: /commit <message>)' },
    { cmd: '/learn',        desc: 'Add a rule to project memory (Usage: /learn <rule>)' },
    { cmd: '/forget',       desc: 'Clear all project memory' },
    { cmd: '/branch',       desc: 'Create new branch (Usage: /branch <branch-name>)' },
    { cmd: '/pr',           desc: 'Open PR from current branch (Usage: /pr <title> [base-branch])' },
    { cmd: '/switch',       desc: 'Switch workspace branch (Usage: /switch <branch>)' },
    { cmd: '/search',       desc: 'Search the web (Usage: /search <query>)' },
    { cmd: '/plan',         desc: 'Analyse repo and create a task plan (Usage: /plan <goal>)' },
    { cmd: '/execute',      desc: 'Execute the next task from the current plan' },
    { cmd: '/review',       desc: 'Review all completed tasks for quality' },
    { cmd: '/autopilot',    desc: 'Run full plan → execute → review loop without prompting' },
    { cmd: '/manual',       desc: 'Return to step-by-step confirmation mode' },
    { cmd: '/pause',        desc: 'Pause the current run after the active task finishes' },
    { cmd: '/tasks',        desc: 'Show tasks in the current milestone' },
    { cmd: '/remember',     desc: 'Save a personal preference (Usage: /remember <preference>)' },
    { cmd: '/forgetme',     desc: 'Clear all personal preferences' },
    { cmd: '/myprefs',      desc: 'Show all saved preferences' },
    { cmd: '/context',      desc: 'Show the current conversation context for this repo/branch' },
    { cmd: '/self-improve', desc: 'Create a branch, plan changes, execute, and open a PR' },
    { cmd: '/rollback',     desc: 'Reset the current branch to match main (undo unmerged changes)' },
    { cmd: '/manifest-build', desc: 'Build or refresh module manifest (commits manifest.json)' },
    { cmd: '/analyze-arch', desc: 'Analyse codebase architecture and store in memory (run /manifest-build first)' },
];
